spring.data.mongodb.uri=mongodb://localhost:27017/reward_game_db
reward.app.jwtSecret=Y8FVVZeJNKbJdcSUNuHl3X3rCP5/rJBSj1gEXRaQKU8BRVyMK4SGlVN9BjbKQCT6cW2y+YKTLhlBr+DCzQHLYA==
reward.app.jwtExpirationMs=86400000
